export const SUGGESTIONS = [
  { city: "Patna", state: "Bihar" },
  { city: "Delhi", state: "Delhi" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Amaravati", state: "Andhra Pradesh" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Dispur", state: "Assam" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Panaji", state: "Goa" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Chandigarh", state: "Haryana" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Imphal", state: "Manipur" },
  { city: "Shillong", state: "Meghalaya" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Gangtok", state: "Sikkim" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Agartala", state: "Tripura" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Srinagar", state: "Jammu and Kashmir" },
];